### PR TITLE
Walljump

### PR DESCRIPTION
**Pull request by dylanjkennedy**
This code waits for the player to let go of the space down button (20, 36, 52, 125-128), then after that checks if they pressed it again and haven't used a walljump yet. (139-143) Next, it checks if they are close to a wall (76-77) and creates an impact away from the wall (79-107) and a movement up (108).

I used an impact, because a move in the x and z direction wasn't working for some reason. I also used the Vector3 static members to get directions like left, right, forward, back. It wouldn't be hard to generate the vectors in other ways I just assume using unity's built it ones is clearer and preferred. I used a overlap sphere of radius 1 from the center, because that covers the player's entire height (which is 2) without going beyond it (which could enable wall jumping off floor or ceiling), while expanding beyond the players own radius (0.5) Also now if you jump twice rapidly against the wall the force of both jumps are added together. If we want the walljump to be set and not added that can be done simply by replacing a "+=" with a "=" in line 108 so that's easy to tweak. 

Note: Looking through I see there are a few places where I have unneeded blank lines. I would fix this before my initial request but it would offset all the line numbers I detailed, so I will just address that with other edits requested. There seem to be a bunch of places where indentation is changed, but I am confused since it seems like the original is very strange like 40-43.

### CODE REVIEW

**Review by LueptowK — CHANGES_REQUESTED** [review]
Overall, good work! The implementation works and seems bug-free to my initial testing. But before we merge it in, there's a few things that I would like changed or fixed.

The biggest problem with the current implementation is that it will not work on walls that are not at a 90 degree angle relative to the world coordinates. The current if/else implementation is a little clumsy anyways, but you should try to figure out a way to get the surface normal of the wall and use that to inform the wallBounceDirection. The simplest way to do this is likely to fire off a quick Raycast into the wall in question, then use RaycastHit.Normal and you'll have the direction.

There should likely be a new value for the walljump impact - you can add it to PlayerValues and then get it in the AirState file. Using jumpSpeed doesn't break things, but you're converting a speed value to an impulse value, and they should be tweakable independently.

Line 135 you may want to add to your if statement that !initialJumpDone, that way we are not redundantly setting the variable every frame the player isn't holding jump.

Nitpicky, but I'd rename "isJumping" to just "jumping" to be more in line with similar variables elsewhere in the project.

Also, to prevent FixedUpdate() from becoming as crowded, it would be preferable to move much if not all of the code in the if (isJumping) block on line 72 into a function or multiple functions, such as DetectNearbyWall() and CalculateWallBounce().

**Comment by LueptowK** [comment]
Oh I forgot - order. Right now the script essentially chooses a random wall within bounds to choose as the walljump wall, instead of choosing the wall that the player is closest to. If you start using a Raycast to get the wall normal as I suggested in a previous comment, that also can be used to solve this problem, as the RaycastHit data can also be used to find distance, I believe, as long as you're sure to raycast towards Collider.ClosestPointOnBounds.

**Comment by dylanjkennedy** [comment]
@LueptowK Made requested changes!

**Review by LueptowK — APPROVED** [review]
Looks great - not much to criticize. 

It may be slightly more accurate to use OverlapCapsule instead of OverlapSphere for the wall detection, but I doubt it is enough of a difference to matter much. If it is, we can revisit that later.

**Comment by dylanjkennedy** [comment]
I thought about using Overlap Capsule and did so originally. But the player height is about 2 and width (radius) is about .5. That means the player's center will never get to be closer than .5 to a wall and enabling it in the 0.5-1 range seemed reasonable. But then to ensure we couldn't wall jump off the ground or ceiling, the max distance up from the center had to also be 1. I started with a capsule and just tweaked it to a sphere.

We *could* have a capsule of height 0.2 and radius 0.9, height 0.4 radius 0.8, height 0.6 radius 0.7, or height 0.8 radius 0.6. All of these would just make wall jumping harder to do in game and it doesn't feel too easy to do right now.

Also regarding non-vertical walls, if the wall is slanted towards the player less than around 45 degrees you can wall jump off it, but beyond that it becomes more like a ceiling. One thing that *may* be a bug, but is more accurately described as a future problem is if the wall is slightly slanted away for you (like at only 10 degrees) you can run up said wall. If we do want non-vertical walls we will have to fix that.

**Pull request merged**
